### PR TITLE
Avoid transient startup crash

### LINKED ISSUE #120: panic: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 10.96.0.1:443: connect: connection refused
When I restart my Docker Desktop on Windows there's a (presumably transient) "connection refused" which causes compose-on-kubernetes to print its command-line arguments and panic.

I see the following:
```
PS C:\Users\djs> kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY   STATUS             RESTARTS   AGE
docker        compose-6c67d745f6-n78x4                 1/1     Running            1          11m
docker        compose-api-57ff65b8c7-5n9zc             0/1     CrashLoopBackOff   1          11m
kube-system   coredns-fb8b8dccf-gvss4                  1/1     Running            3          13m
kube-system   coredns-fb8b8dccf-wwq9z                  1/1     Running            3          13m
kube-system   etcd-docker-desktop                      1/1     Running            1          12m
kube-system   kube-apiserver-docker-desktop            1/1     Running            1          12m
kube-system   kube-controller-manager-docker-desktop   1/1     Running            1          12m
kube-system   kube-proxy-qcld8                         1/1     Running            1          13m
kube-system   kube-scheduler-docker-desktop            1/1     Running            1          12m
PS C:\Users\djs> kubectl logs -n docker compose-api-57ff65b8c7-5n9zc
I0724 14:31:56.884772       1 client.go:352] parsed scheme: ""
I0724 14:31:56.884881       1 client.go:352] scheme "" not registered, fallback to default scheme
I0724 14:31:56.885429       1 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{127.0.0.1:2379 0  <nil>}]
I0724 14:31:56.885994       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
I0724 14:31:56.906510       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
Error: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 10.96.0.1:443: connect: connection refused
Usage:
   [flags]

Flags:
      --admission-control-config-file string                    File with admission control configuration.
      --audit-dynamic-configuration                             Enables dynamic audit configuration. This feature also requires the DynamicAuditing feature flag
      --audit-log-batch-buffer-size int                         The size of the buffer to store events before batching and writing. Only used in batch mode. (default 10000)
      --audit-log-batch-max-size int                            The maximum size of a batch. Only used in batch mode. (default 1)
      --audit-log-batch-max-wait duration                       The amount of time to wait before force writing the batch that hadn't reached the max size. Only used in batch mode.
      --audit-log-batch-throttle-burst int                      Maximum number of requests sent at the same moment if ThrottleQPS was not utilized before. Only used in batch mode.
      --audit-log-batch-throttle-enable                         Whether batching throttling is enabled. Only used in batch mode.
      --audit-log-batch-throttle-qps float32                    Maximum average number of batches per second. Only used in batch mode.
      --audit-log-format string                                 Format of saved audits. "legacy" indicates 1-line text format for each event. "json" indicates structured json format. Known formats are legacy,json. (default "json")
      --audit-log-maxage int                                    The maximum number of days to retain old audit log files based on the timestamp encoded in their filename.
      --audit-log-maxbackup int                                 The maximum number of old audit log files to retain.
      --audit-log-maxsize int                                   The maximum size in megabytes of the audit log file before it gets rotated.
      --audit-log-mode string                                   Strategy for sending audit events. Blocking indicates sending events should block server responses. Batch causes the backend to buffer and write events asynchronously. Known modes are batch,blocking,blocking-strict. (default "blocking")
      --audit-log-path string                                   If set, all requests coming to the apiserver will be logged to this file.  '-' means standard out.
      --audit-log-truncate-enabled                              Whether event and batch truncating is enabled.
      --audit-log-truncate-max-batch-size int                   Maximum size of the batch sent to the underlying backend. Actual serialized size can be several hundreds of bytes greater. If a batch exceeds this limit, it is split into several batches of smaller size. (default 10485760)
      --audit-log-truncate-max-event-size int                   Maximum size of the audit event sent to the underlying backend. If the size of an event is greater than this number, first request and response are removed, and if this doesn't reduce the size enough, event is discarded. (default 102400)
      --audit-log-version string                                API group and version used for serializing audit events written to log. (default "audit.k8s.io/v1")
      --audit-policy-file string                                Path to the file that defines the audit policy configuration.
      --audit-webhook-batch-buffer-size int                     The size of the buffer to store events before batching and writing. Only used in batch mode. (default 10000)
      --audit-webhook-batch-max-size int                        The maximum size of a batch. Only used in batch mode. (default 400)
      --audit-webhook-batch-max-wait duration                   The amount of time to wait before force writing the batch that hadn't reached the max size. Only used in batch mode. (default 30s)
      --audit-webhook-batch-throttle-burst int                  Maximum number of requests sent at the same moment if ThrottleQPS was not utilized before. Only used in batch mode. (default 15)
      --audit-webhook-batch-throttle-enable                     Whether batching throttling is enabled. Only used in batch mode. (default true)
      --audit-webhook-batch-throttle-qps float32                Maximum average number of batches per second. Only used in batch mode. (default 10)
      --audit-webhook-config-file string                        Path to a kubeconfig formatted file that defines the audit webhook configuration.
      --audit-webhook-initial-backoff duration                  The amount of time to wait before retrying the first failed request. (default 10s)
      --audit-webhook-mode string                               Strategy for sending audit events. Blocking indicates sending events should block server responses. Batch causes the backend to buffer and write events asynchronously. Known modes are batch,blocking,blocking-strict. (default "batch")
      --audit-webhook-truncate-enabled                          Whether event and batch truncating is enabled.
      --audit-webhook-truncate-max-batch-size int               Maximum size of the batch sent to the underlying backend. Actual serialized size can be several hundreds of bytes greater. If a batch exceeds this limit, it is split into several batches of smaller size. (default 10485760)
      --audit-webhook-truncate-max-event-size int               Maximum size of the audit event sent to the underlying backend. If the size of an event is greater than this number, first request and response are removed, and if this doesn't reduce the size enough, event is discarded. (default 102400)
      --audit-webhook-version string                            API group and version used for serializing audit events written to webhook. (default "audit.k8s.io/v1")
      --authentication-kubeconfig string                        kubeconfig file pointing at the 'core' kubernetes server with enough rights to create tokenaccessreviews.authentication.k8s.io.
      --authentication-skip-lookup                              If false, the authentication-kubeconfig will be used to lookup missing authentication configuration from the cluster.
      --authentication-token-webhook-cache-ttl duration         The duration to cache responses from the webhook token authenticator. (default 10s)
      --authentication-tolerate-lookup-failure                  If true, failures to look up missing authentication configuration from the cluster are not considered fatal. Note that this can result in authentication that treats all requests as anonymous.
      --authorization-always-allow-paths strings                A list of HTTP paths to skip during authorization, i.e. these are authorized without contacting the 'core' kubernetes server.
      --authorization-kubeconfig string                         kubeconfig file pointing at the 'core' kubernetes server with enough rights to create subjectaccessreviews.authorization.k8s.io.
      --authorization-webhook-cache-authorized-ttl duration     The duration to cache 'authorized' responses from the webhook authorizer. (default 10s)
      --authorization-webhook-cache-unauthorized-ttl duration   The duration to cache 'unauthorized' responses from the webhook authorizer. (default 10s)
      --bind-address ip                                         The IP address on which to listen for the --secure-port port. The associated interface(s) must be reachable by the rest of the cluster, and by CLI/web clients. If blank, all interfaces will be used (0.0.0.0 for all IPv4 interfaces and :: for all IPv6 interfaces). (default 0.0.0.0)
      --ca-bundle-file string                                   defines the path to the CA bundle file
      --cert-dir string                                         The directory where the TLS certs are located. If --tls-cert-file and --tls-private-key-file are provided, this flag will be ignored. (default "apiserver.local.config/certificates")
      --client-ca-file string                                   If set, any request presenting a client certificate signed by one of the authorities in the client-ca-file is authenticated with an identity corresponding to the CommonName of the client certificate.
      --contention-profiling                                    Enable lock contention profiling, if profiling is enabled
      --default-watch-cache-size int                            Default watch cache size. If zero, watch cache will be disabled for resources that do not have a default watch size set. (default 100)
      --delete-collection-workers int                           Number of workers spawned for DeleteCollection call. These are used to speed up namespace cleanup. (default 1)
      --disable-admission-plugins strings                       admission plugins that should be disabled although they are in the default enabled plugins list (NamespaceLifecycle, MutatingAdmissionWebhook, ValidatingAdmissionWebhook). Comma-delimited list of admission plugins: MutatingAdmissionWebhook, NamespaceLifecycle, ValidatingAdmissionWebhook. The order of plugins in this flag does not matter.
      --enable-admission-plugins strings                        admission plugins that should be enabled in addition to default enabled ones (NamespaceLifecycle, MutatingAdmissionWebhook, ValidatingAdmissionWebhook). Comma-delimited list of admission plugins: MutatingAdmissionWebhook, NamespaceLifecycle, ValidatingAdmissionWebhook. The order of plugins in this flag does not matter.
      --enable-garbage-collector                                Enables the generic garbage collector. MUST be synced with the corresponding flag of the kube-controller-manager. (default true)
      --encryption-provider-config string                       The file containing configuration for encryption providers to be used for storing secrets in etcd
      --etcd-cafile string                                      SSL Certificate Authority file used to secure etcd communication.
      --etcd-certfile string                                    SSL certification file used to secure etcd communication.
      --etcd-compaction-interval duration                       The interval of compaction requests. If 0, the compaction request from apiserver is disabled. (default 5m0s)
      --etcd-count-metric-poll-period duration                  Frequency of polling etcd for number of resources per type. 0 disables the metric collection. (default 1m0s)
      --etcd-keyfile string                                     SSL key file used to secure etcd communication.
      --etcd-prefix string                                      The prefix to prepend to all resource paths in etcd. (default "/registry/docker.com/stacks")
      --etcd-servers strings                                    List of etcd servers to connect with (scheme://ip:port), comma separated.
      --etcd-servers-overrides strings                          Per-resource etcd servers overrides, comma separated. The individual override format: group/resource#servers, where servers are URLs, semicolon separated.
      --healthz-check-port int                                  defines the port used by healthz check server (0 to disable it) (default 8080)
  -h, --help                                                    help for this command
      --http2-max-streams-per-connection int                    The limit that the server gives to clients for the maximum number of streams in an HTTP/2 connection. Zero means to use golang's default. (default 1000)
      --kubeconfig string                                       kubeconfig file pointing at the 'core' kubernetes server.
      --log-flush-frequency duration                            Maximum number of seconds between log flushes (default 5s)
      --profiling                                               Enable profiling via web interface host:port/debug/pprof/ (default true)
      --requestheader-allowed-names strings                     List of client certificate common names to allow to provide usernames in headers specified by --requestheader-username-headers. If empty, any client certificate validated by the authorities in --requestheader-client-ca-file is allowed.
      --requestheader-client-ca-file string                     Root certificate bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified by --requestheader-username-headers. WARNING: generally do not depend on authorization being already done for incoming requests.
      --requestheader-extra-headers-prefix strings              List of request header prefixes to inspect. X-Remote-Extra- is suggested. (default [x-remote-extra-])
      --requestheader-group-headers strings                     List of request headers to inspect for groups. X-Remote-Group is suggested. (default [x-remote-group])
      --requestheader-username-headers strings                  List of request headers to inspect for usernames. X-Remote-User is common. (default [x-remote-user])
      --secure-port int                                         The port on which to serve HTTPS with authentication and authorization.If 0, don't serve HTTPS at all. (default 443)
      --service-name string                                     defines the name of the service exposing the aggregated API
      --service-namespace string                                defines the namespace of the service exposing the aggregated API
      --storage-backend string                                  The storage backend for persistence. Options: 'etcd3' (default).
      --storage-media-type string                               The media type to use to store objects in storage. Some resources or storage backends may only support a specific media type and will ignore this setting. (default "application/json")
      --tls-cert-file string                                    File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert). If HTTPS serving is enabled, and --tls-cert-file and --tls-private-key-file are not provided, a self-signed certificate and key are generated for the public address and saved to the directory specified by --cert-dir.
      --tls-cipher-suites strings                               Comma-separated list of cipher suites for the server. If omitted, the default Go cipher suites will be use.  Possible values: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_RC4_128_SHA
      --tls-min-version string                                  Minimum TLS version supported. Possible values: VersionTLS10, VersionTLS11, VersionTLS12
      --tls-private-key-file string                             File containing the default x509 private key matching --tls-cert-file.
      --tls-sni-cert-key namedCertKey                           A pair of x509 certificate and private key file paths, optionally suffixed with a list of domain patterns which are fully qualified domain names, possibly with prefixed wildcard segments. If no domain patterns are provided, the names of the certificate are extracted. Non-wildcard matches trump over wildcard matches, explicit domain patterns trump over extracted names. For multiple key/certificate pairs, use the --tls-sni-cert-key multiple times. Examples: "example.crt,example.key" or "foo.crt,foo.key:*.foo.com,foo.com". (default [])
      --watch-cache                                             Enable watch caching in the apiserver (default true)
      --watch-cache-sizes strings                               Watch cache size settings for some resources (pods, nodes, etc.), comma separated. The individual setting format: resource[.group]#size, where resource is lowercase plural (no version), group is omitted for resources of apiVersion v1 (the legacy core API) and included for others, and size is a number. It takes effect when watch-cache is enabled. Some resources (replicationcontrollers, endpoints, nodes, pods, services, apiservices.apiregistration.k8s.io) have system defaults set by heuristics, others default to default-watch-cache-size

panic: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 10.96.0.1:443: connect: connection refused

goroutine 1 [running]:
main.main()
        /go/src/github.com/docker/compose-on-kubernetes/cmd/api-server/main.go:17 +0x5a
PS C:\Users\djs>
```
A little while later the other pod failed: (presumably this is a cascade failure)
```
PS C:\Users\djs> kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY   STATUS                 RESTARTS   AGE
docker        compose-6c67d745f6-n78x4                 0/1     CrashLoopBackOff       1          20m
docker        compose-api-57ff65b8c7-5n9zc             0/1     CreateContainerError   1          20m
kube-system   coredns-fb8b8dccf-gvss4                  1/1     Running                3          22m
kube-system   coredns-fb8b8dccf-wwq9z                  1/1     Running                3          22m
kube-system   etcd-docker-desktop                      1/1     Running                1          21m
kube-system   kube-apiserver-docker-desktop            1/1     Running                1          21m
kube-system   kube-controller-manager-docker-desktop   1/1     Running                1          21m
kube-system   kube-proxy-qcld8                         1/1     Running                1          22m
kube-system   kube-scheduler-docker-desktop            1/1     Running                1          21m
PS C:\Users\djs> kubectl logs -n docker compose-6c67d745f6-n78x4
Version:    v0.4.23
Git commit: cc4914d
OS/Arch:    linux/amd64
Built:      Wed Jun  5 12:33:17 2019
W0724 15:31:53.121828       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2019-07-24T14:42:17Z" level=fatal msg="cannot watch stacks"
```

### PR DESCRIPTION
**Pull request by djs55**
When the Kubernetes cluster is starting, the compose-api server startup can fail because the `o.RecommendedOptions.ApplyTo` will call into `o.Authentication.ApplyTo` which will call into
`lookupMissingConfigInCluster` which can fail to `Dial` the API server to query a config map because the API server has not fully started yet. This manifests as a panic and a print of the program's arguments.

This patch looks for this kind of transient `connection refused` error, logs and retries again in 5s so
- we don't panic() in the logs in a common / expected case
- we don't rely on Kubernetes restarting the pod during normal startup

This should fix #120

Note there is already precedent for retrying connection refused errors instead of crashing; for example:

```
W0725 10:31:53.877550       1 clientconn.go:1240] grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
```

I tested this locally by patching the vendored k8s.io code to dial the wrong address 5 times. I saw the expected log entries 5 times and then it succeeded.

### CODE REVIEW

File: cmd/api-server/cli/root.go [hunk 1]
```diff
@@ -60,7 +60,17 @@ func NewCommandStartComposeServer(stopCh <-chan struct{}) *cobra.Command {
...
 				return err
 			}
-			return runComposeServer(o, stopCh)
+			for {
+				err := runComposeServer(o, stopCh)
+				// If the compose-api starts before the API server is listening then we can get a transient connection refused
+				// while looking up missing authentication information in the cluster (see #120).
+				if err != nil && strings.HasSuffix(err.Error(), "connection refused") {
+					fmt.Fprintf(os.Stderr, "unable to start compose server: %s. Will retry in 5s\n", err)
+					time.Sleep(5 * time.Second)
```
Comment (silvin-lubecki) [inline cmd/api-server/cli/root.go]: Shouldn't we use exponential backoff instead, and maybe for a limited number of attempts?

File: cmd/api-server/cli/root.go [hunk 2]
```diff
@@ -60,7 +60,17 @@ func NewCommandStartComposeServer(stopCh <-chan struct{}) *cobra.Command {
 			if err := utilerrors.NewAggregate(errors); err != nil {
 				return err
 			}
-			return runComposeServer(o, stopCh)
+			for {
+				err := runComposeServer(o, stopCh)
+				// If the compose-api starts before the API server is listening then we can get a transient connection refused
+				// while looking up missing authentication information in the cluster (see #120).
+				if err != nil && strings.HasSuffix(err.Error(), "connection refused") {
```
Comment (silvin-lubecki) [inline cmd/api-server/cli/root.go]: Depending on error content is somehow fragile, even if I guess there's no other way to catch this one... Maybe using `contains` would be a "little" more robust on changes ?

File: cmd/api-server/cli/root.go (hunk 1 above)
Comment (djs55) [reply cmd/api-server/cli/root.go]: Good idea. I've pushed a patch to switch to exponential backoff: 1s, 2s, 4s, ..., 128s and then stop. (Let me know if you'd like me to squash it later)

File: cmd/api-server/cli/root.go (hunk 2 above)
Comment (djs55) [reply cmd/api-server/cli/root.go]: Good point. I've pushed a patch switching to `Contains` instead of `HasSuffix`.

I had a go at doing something more precise yesterday to see what it would look like. From memory I think you have to do something like
```golang
if urlError, ok := err.(*url.Error); ok {
  if opError, ok := urlError.Err.(*net.OpError); ok {
     if syscallError, ok := opError.Err.(*os.SyscallError); ok {
       // at this point it probably has "connect" in it
     }
  }
}
```
Some of those error types have `Temporary()` functions which I hoped I could use but they all returned `false` when I tried it.
Let me know what you prefer! :)

Comment (silvin-lubecki) [reply cmd/api-server/cli/root.go]: I'm good with the `contains` 😄

**Comment by silvin-lubecki** [comment]
@djs55  The linter is complaining:
```
cmd/api-server/cli/root.go:1::warning: file is not goimported (goimports)
```

**Comment by silvin-lubecki** [comment]
cc @simonferquel @rumpl

**Comment by djs55** [comment]
> @djs55 The linter is complaining:
> 
> ```
> cmd/api-server/cli/root.go:1::warning: file is not goimported (goimports)
> ```

oops, sorry. I've force-pushed a `gofmt -w -s` of the broken patch.

**Comment by djs55** [comment]
Thanks!
